# Generated by Django 5.1.3 on 2024-11-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_fecha',
            field=models.DateField(default='2024-11-19'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ArtPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField()),
                ('id_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_app.art')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_app.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='pregunta',
            field=models.ManyToManyField(through='art_app.ArtPregunta', to='art_app.pregunta'),
        ),
    ]
