# Generated by Django 5.1 on 2024-11-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0002_artempleado_alter_art_empleado'),
        ('personal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artempleado',
            old_name='emp_id',
            new_name='empleado_id',
        ),
        migrations.RemoveField(
            model_name='artempleado',
            name='estado_art',
        ),
        migrations.RemoveField(
            model_name='artempleado',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='artempleado',
            name='supervisor_asignado',
        ),
        migrations.AddField(
            model_name='artempleado',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='empleado',
            field=models.ManyToManyField(through='art_app.ArtEmpleado', to='personal_app.empleado'),
        ),
    ]
